# The Docker image to run your workspace in.
image: gitpod/workspace-mysql

# Command to start on workspace startup
tasks:
  - init: |
      mysql -e "CREATE DATABASE IF NOT EXIST laravel;" 
      composer install
      php artisan migrate --force
  command: |
    export DB_HOST=localhost
    export DB_USERNAME=root
    export DB_PASSWORD=
    export DB_DATABASE=laravel
    php artisan serve
  
# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: open-preview
  